version: "3.9"

services:
  backend:
    build:
      context: . 
      dockerfile: ./backend/Dockerfile 
    ports:
      - "8081:8081"
    volumes:
      - sqlite-data:/database/sqlite
    environment: 
      - GO_ENV
      - DOMAIN
      - CORS_DOMAIN
    networks:
      - realtime_forum

  frontend:
    build:
      context: . 
      dockerfile: ./frontend/Dockerfile 
    ports:
      - "8080:8080"
    environment: 
      - GO_ENV
    networks:
      - realtime_forum

volumes:
  sqlite-data: 

networks:
  realtime_forum:
    name: realtime_forum


